### YamlMime:ManagedReference
items:
- uid: Library_Web_Application.Extensions
  commentId: N:Library_Web_Application.Extensions
  id: Library_Web_Application.Extensions
  children:
  - Library_Web_Application.Extensions.ExceptionMiddlewareExtensions
  langs:
  - csharp
  - vb
  name: Library_Web_Application.Extensions
  nameWithType: Library_Web_Application.Extensions
  fullName: Library_Web_Application.Extensions
  type: Namespace
  assemblies:
  - BooksManagementService
references:
- uid: Library_Web_Application.Extensions.ExceptionMiddlewareExtensions
  commentId: T:Library_Web_Application.Extensions.ExceptionMiddlewareExtensions
  href: Library_Web_Application.Extensions.ExceptionMiddlewareExtensions.html
  name: ExceptionMiddlewareExtensions
  nameWithType: ExceptionMiddlewareExtensions
  fullName: Library_Web_Application.Extensions.ExceptionMiddlewareExtensions
